### ISSUE TITLE
Not bumped 0.5.0 to crates.io

### ISSUE THREAD

**Issue by wendajiang** [uttarayan21/ansi-to-tui#12]

**Comment by sayanarijit** [comment]
@uttarayan21 Could you please release this?

**Comment by uttarayan21** [comment]
I pushed the v0.5.0 to crates.io.
It contains a known bug #10

**Comment by uttarayan21** [comment]
#10 Should be fixed on master now with #13 . And I've created a v0.5.1 with the pr
