### ISSUE TITLE
ansi to text returns empty string when there's no color code

### ISSUE THREAD

**Issue by sayanarijit** [uttarayan21/ansi-to-tui#2]
To reproduce

```rust
#[test]
fn test_string() {
    let string = "FOO".to_string();
    println!("{:?}", ansi_to_text(string.bytes()));
}
```

**Comment by uttarayan21** [comment]
Thanks for the bug report.
I pushed a commit that should fix it.

**Comment by sayanarijit** [comment]
Awesome, thanks. Waiting for the next release. For now, I'm using this hack https://github.com/sayanarijit/xplr/pull/188/commits/bee14f454a4102493e27bb6d1241e89943c91e35#diff-acf9ca25b7b2d13e11c1035ebbda4140466603739b73a371b67a9a267d0ce626R557-R563

**Comment by uttarayan21** [comment]
Great !
I'll publish a release once I do some testing.
Should be up later today.

**Comment by uttarayan21** [comment]
I have published an updated version in [crates.io/crates/ansi-to-tui](https://crates.io/crates/ansi-to-tui). Thanks for reporting the issue.
