### ISSUE TITLE
Additionally getting a String with all ANSI characters stripped

### ISSUE THREAD

**Issue by fritzrehde** [uttarayan21/ansi-to-tui#33]
Hi, great library! One need I currently have is to parse an input string that contains ANSI color characters/codes into a ratatui `Text` for displaying it in the TUI, but I also need to store an unformatted (meaning all ANSI color codes removed) string separately as well.
My first thought is: Can I somehow extract the raw string saved in `Text`? This would obviously not contain the ANSI codes directly anymore. But I didn't find any suitable methods in ratatui's `Text`. Does anybody know if this is possible?
My second thought: I guess maybe I could use a separate library to do this, but it seems like that would result in duplicated effort. This library seems to already remove the ANSI codes (and convert them to ratatui `Style` items), so why parse the string again.
I'm not that familiar with Rust library API design, so I'm not sure if this functionality should be implemented inside this library directly, or if the feature I proposed, extracting raw string from a ratatui `Text`, should be implemented in ratatui.
Thanks for creating this awesome library!

**Comment by uttarayan21** [comment]
Since all text is stored in `Cow<'a, str>` form and all of it's fields are public you can actually get the string without any library.

```rust
    let string = "\x1b[33mYellow\x1b[31mRed\x1b[32mGreen\x1b[0m";
    let text = string.into_text().unwrap();
    let stripped = text
        .lines
        .iter()
        .map(|line| {
            line.spans
                .iter()
                .map(|span| span.content.clone())
                .collect::<String>()
        })
        .collect::<Vec<String>>()
        .join("\n");
    assert_eq!(stripped, "YellowRedGreen");
```
Here is a basic example of what you can do.  
Thank you for the kind words as well.

**Comment by fritzrehde** [comment]
Ok, thanks! I'm using that for now then, though I do think it is something that should maybe be provided by ratatui directly, especially because exposing pub member isn't really good practice in Rust, if I remember correctly (though maybe there is some other reason these members are public). Do you think I should create a PR in ratatui for adding something like this as a `ToString` trait impl or similar?

**Comment by uttarayan21** [comment]
If you want you can open a PR.
However do consider that this is an expensive operation with a bunch of heap allocations.

I'll close this issue if it's solved then.
