### ISSUE TITLE
Incompatibility with ratatui v0.26.0

### ISSUE THREAD

**Issue by julianbuettner** [uttarayan21/ansi-to-tui#35]
I want to update to ratatui to v0.26.0, but it includes at least one breaking change, which makes the structs emitted by ansi-to-tui incompatible with the new version of ratatui. 
Maybe the new `style` field in `Line`? [breaking changes](https://github.com/ratatui-org/ratatui/blob/main/BREAKING-CHANGES.md)

Please consider updating the ratatui dependency.

**Comment by TheRealLorenz** [comment]
After testing this crate against 0.26.0, I haven't found any error with the current implementation. There's just one test which is broken but I don't think it's related in any way.

**Comment by uttarayan21** [comment]
Can you try doing a  `cargo tree -i ratatui` and paste the output here ?

**Comment by julianbuettner** [comment]
Hi, I worked with two crates and mixed something up of where which ratatui version was used. I am sorry. Everything works fine. Thank you for your readiness and wilingness to help.

**Comment by uttarayan21** [comment]
Yeah it's a semver hazard like mentioned in the issue #32 From the next release onward I'll make a new release for every ratatui update.
