### ISSUE TITLE
Breaking changes in ratatui 0.27.0 + ansi-to-tui open to 0.27.0 in version constraints causing issues where cargo.lock ignored

### ISSUE THREAD

**Issue by robertpsoane** [uttarayan21/ansi-to-tui#47]
I am getting an issue wherein with the new version of ratatui (unable to upgrade _today_ due to other dependencies) when I `cargo install` and the cargo.lock is ignored, ansi-to-tui is pulling in 0.27.0, as well as the 0.26.3 I'm already using.

To abet this I propose #46 for the next patch, then following up with the bump to 0.27.0

This will allow lagging projects to pin to a version of ansi-to-tui (potentially only in the short term) and avoid sudden breakage

**Comment by uttarayan21** [comment]
Yeah this is the same issue as the pinned issue.
For this I'll merge your pr and release a minor version of the 4.1. And from 0.27 onwards I'll make a major release of this crate corresponding to minor versions of ratatui.

**Comment by uttarayan21** [comment]
Merged
