### ISSUE TITLE
0.2.2 breaks dependency resolution

### ISSUE THREAD

**Issue by sayanarijit** [uttarayan21/ansi-to-tui#5]
Hi, as observed in https://github.com/sayanarijit/xplr/issues/208#issuecomment-852115184, the version `0.2.2` broke `xplr` compilation.

As per https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies-from-cratesio, `0.2.0` is equivalent to `^0.2.0`, which means the last upgrade should have been a major version upgrade instead of bugfix release.

**Comment by uttarayan21** [comment]
Oh thanks for letting me know ! I'll yank the release and publish a v0.3.0

**Comment by uttarayan21** [comment]
I've now published [v0.3.0](https://crates.io/crates/ansi-to-tui/0.3.0). And yanked v0.2.2

**Comment by sayanarijit** [comment]
FIxed. Thanks for your super quick response.
