### ISSUE TITLE
Is it a naive implementation?

### ISSUE THREAD

**Issue by grtcdr** [uttarayan21/ansi-to-tui#8]
It seems to me like `ansi-to-tui` is very stable for the two dependents on your crate, so you might as well get rid of the last sentence in the README. It could deter some people and I for one think more people should be using this :)

**Comment by uttarayan21** [comment]
You are right.
 However I do think it's a naive implementation. Since I'm reading bytes one by one and parsing them. There could be a better way to process this.
I'll remove it for now.

**Comment by grtcdr** [comment]
> However I do think it's a naive implementation. Since I'm reading bytes one by one and parsing them. There could be a better way to process this.

What other ways are more efficient? I would say caching could improve it, but it's not a slow library whatsoever.

**Comment by uttarayan21** [comment]
That's true it's not slow, and I don't have a way to improve it. But since it is a basic approach there maybe ways to improve it which I don't know of. Also caching could work but it's too much of a hassle to add right now.

**Comment by grtcdr** [comment]
Yeah cache AFAIK is quite hard to implement properly, and it's really not needed anyways since the program is still super fast (at least for ASCII art which usually isn't that big).
