### ISSUE TITLE
Color resets do not work

### ISSUE THREAD

**Issue by Ewpratten** [uttarayan21/ansi-to-tui#9]
Given any string built in the following way:

 1. Color is set
 2. Text
 3. Color is **reset** (`\033[0m`)
 4. More text

The "More text" will keep the color of the first text.

My quick fix is to do the following:

```rust
ansi_to_text(my_string.replace("[0m", "[39m").bytes())
```

**Comment by uttarayan21** [comment]
I'll take a look.
Probably a bug in optimization.

**Comment by uttarayan21** [comment]
Can you check If it works for you in  the linked commit ? If it still doesn't work feel free to reopen.
